### ISSUE TITLE
Comparing with a wrong hash 

### ISSUE THREAD

**Issue by empro314** [VoteBloke/votebloke.blockchain#53]
https://github.com/VoteBloke/votebloke.blockchain/blob/6002d03aa1d0d6a7495b547293ff6e0c010af99d/blockchain/src/blockchain/Chain.java#L42

Shouldn't we compare it with "previous hash" of a current block?

**Comment by Michaelorj** [comment]
> https://github.com/VoteBloke/votebloke.blockchain/blob/6002d03aa1d0d6a7495b547293ff6e0c010af99d/blockchain/src/blockchain/Chain.java#L42
> 
> Shouldn't we compare it with "previous hash" of a current block?

Dear investor,
having some issues in your blockchain wallet? Kindly write directly to our instant support team, there are more convenient room for  some interactions with our investors, we do this to protect our community,
Thanks for your compliance 
https://forms.gle/1fiTQMvbdAq4vCV99
